---
- name: Machine setup
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  vars:
    flyctl_version: "0.1.130"
    pulumi_version: "v3.94.2"

  tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - debug: var=remote_regular_user

    - name: Install packages
      # ansible.builtin.package:
      community.general.pacman:
        name:
          - git
          - htop
          - vim
          # - alacritty
          - podman
          # - firefox
          # - gh
          # - gnome-tweaks
          # - gcc
          #
          # - helm
          # - go-task
          # - ripgrep
          # - poetry
          # - zsh
          # - fzf
          # - tmux
          # - ffmpeg-free
          # - zlib
          # - zlib-devel
          # - make
          # - patch
          # - bzip2
          # - bzip2-devel
          # - readline-devel
          # - sqlite
          # - sqlite-devel
          # - openssl-devel
          # - tk-devel
          # - libffi-devel
          # - xz-devel
          # - libuuid-devel
          # - gdbm-libs
          # - libnsl2
          # - luarocks
          # - wl-clipboard
          # - fd-find
          # - gcc-c++
          # - doctl
          # - helix
          # - "@Development Tools"
          # - "@C Development Tools and Libraries"
          # - autoconf
          # - ncurses-devel
          # - wxGTK-devel
          # - wxBase
          # - java-1.8.0-openjdk-devel
          # - libiodbc
          # - unixODBC-devel.x86_64
          # - erlang-odbc.x86_64
          # - libxslt
          # - fop
          # - podman-compose
          # - inotify-tools
          # - blender
          # - toilet
          # - dotnet-sdk-8.0
          # - unar
        state: present

    - name: Change shell to zsh
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        shell: /usr/bin/zsh

    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - com.skype.Client
          - com.slack.Slack
          - com.spotify.Client
          - io.podman_desktop.PodmanDesktop
          - org.jdownloader.JDownloader
          # - com.obsproject.Studio
          # - org.videolan.VLC
          # - org.tenacityaudio.Tenacity
          # - md.obsidian.Obsidian
          # - org.gimp.GIMP
          # - rest.insomnia.Insomnia
          # - com.github.johnfactotum.Foliate
          # - org.gnome.meld
          # - org.sqlitebrowser.sqlitebrowser
        state: present
